// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVvGwKis9FJBVLkgRn0sBOCgn2tSBfcQ',
    appId: '1:583892819692:web:7c6b0d6f939b9db36c4fc9',
    messagingSenderId: '583892819692',
    projectId: 'lightstep-68da4',
    authDomain: 'lightstep-68da4.firebaseapp.com',
    storageBucket: 'lightstep-68da4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKyJH9RpH8MZrUHQ21jrofYh4Lpg5iB8Y',
    appId: '1:583892819692:android:480f5558b32028ea6c4fc9',
    messagingSenderId: '583892819692',
    projectId: 'lightstep-68da4',
    storageBucket: 'lightstep-68da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeiRTsMcZ-ov6sPFe2mQqpKb2t7HOhHY',
    appId: '1:583892819692:ios:57e480a7eceacd066c4fc9',
    messagingSenderId: '583892819692',
    projectId: 'lightstep-68da4',
    storageBucket: 'lightstep-68da4.firebasestorage.app',
    iosBundleId: 'com.example.lightStepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxeiRTsMcZ-ov6sPFe2mQqpKb2t7HOhHY',
    appId: '1:583892819692:ios:57e480a7eceacd066c4fc9',
    messagingSenderId: '583892819692',
    projectId: 'lightstep-68da4',
    storageBucket: 'lightstep-68da4.firebasestorage.app',
    iosBundleId: 'com.example.lightStepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeVvGwKis9FJBVLkgRn0sBOCgn2tSBfcQ',
    appId: '1:583892819692:web:595735e2d0d010a96c4fc9',
    messagingSenderId: '583892819692',
    projectId: 'lightstep-68da4',
    authDomain: 'lightstep-68da4.firebaseapp.com',
    storageBucket: 'lightstep-68da4.firebasestorage.app',
  );
}
